apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-application
  namespace: myapp
spec:
  project: default

  source:
    repoURL: https://github.com/azitmentor/cicdtest.git
    targetRevision: HEAD
    path: .
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

