name: Docker build to github container registry

on:
  push:
    branches: [ ghadockertest ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3  
    
    - name: Docker login
      uses: docker/login-action@v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}          
#    - name: Build the Docker image
#      run: docker build ./cicdtest -f cicdtest/Dockerfile --tag lakycr.azurecr.io/cicdtest
#    - name: Push Docker image
#      run: docker push lakycr.azurecr.io/cicdtest
#
#    - name: 'Build and push image'
#      uses: azure/docker-login@v1
#      with:
#        login-server: lakycr.azurecr.io
#        username: lakycr
#        password: ${{ secrets.azurepw }}
#    - run: |
#        docker build ./cicdtest -f cicdtest/Dockerfile --tag lakycr.azurecr.io/cicdtest
#        docker push lakycr.azurecr.io/cicdtest
#    - uses: actions/checkout@v3
    # - name: 'build and push'
    #   run: |
    #     docker build ./cicdtest -f cicdtest/Dockerfile --tag cicdtest:latest
    #     docker push cicdtest:latest
    - name: 'output variables'
      run: |
        echo "adatok"
        echo ${{ steps.meta.outputs }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./cicdtest
        push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}        
#tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
