name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: docker build ./cicdtest -f cicdtest/Dockerfile --tag lakycr.azurecr.io/cicdtest
#    - name: Push Docker image
#      run: docker push lakycr.azurecr.io/cicdtest

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: lakycr.azurecr.io
        username: lakycr
        password: secrets.azurepw
    - run: |
        docker build ./cicdtest -f cicdtest/Dockerfile --tag lakycr.azurecr.io/cicdtest
        docker push lakycr.azurecr.io/cicdtest
