name: Docker Image CI

on:
  push:
    branches: [ k3stest ]
  pull_request:
    branches: [ k3stest ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
     - uses: actions-hub/kubectl@master
  env:
    KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  with:
    args: get pods
